### ISSUE TITLE
TypeError when using with vue-test-utils mount

### ISSUE THREAD

**Issue by subtlegiant** [webalys-hq/streamline-wrapper-vue#4]
I am unable to use mount via vue-test-utils, doing so produces the following error:

```
console.error
    TypeError: _vm._ssrAttr is not a function
        at Proxy.__vue_render__$1 (node_modules/@streamlinehq/streamline-wrapper-vue/dist/streamline-wrapper-vue.ssr.js:301:33)
```

**Comment by cbrwizard** [comment]
Hello, we have just released a completely new universal npm package which is much more performant than before and solves all license sync issues. It requires a bit different setup but it's more straightforward. We know that migrating can be confusing but once it's done we believe it will provide better experience for you. I believe it will solve the issue you've mentioned as well.

Once you set it up you will be able to import the Streamline icons you own in a form of plain and simple svg files. This package will also not bloat your project with the files you don't need.

Please check it out here https://github.com/webalys-hq/streamlinehq-npm. If you have any issues for it or suggestions about it please open an issue there.
